apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: ${NS_NAME}
data:
  RABBIT_URL: ${RABBIT_URL}
  REDIS_URL: ${REDIS_URL}
  SERVER_ADDR: ${SERVER_ADDR}
  EXCHANGE: ${EXCHANGE}
  QUEUE_BACK: ${QUEUE_BACK}
  QUEUE_DB: ${QUEUE_DB}
  QUEUE_CACHE: ${QUEUE_CACHE}
  KEY_FRONT: ${KEY_FRONT}
  KEY_BACK: ${KEY_BACK}
  KEY_DB: ${KEY_DB}
  KEY_CACHE: ${KEY_CACHE}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-db-config
  namespace: ${NS_NAME}
data:
  database.sql: |
    create database microservices;

    \c microservices

    create table messages (
      id serial primary key,
      message text not null,
      created timestamp not null
    );

