apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: dev
type: Opaque
data:
  POSTGRES_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpkZW1vcHN3QHBvc3RncmVzLmRldi5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL21pY3Jvc2VydmljZXM=
  POSTGRES_PASSWORD: ZGVtb3Bzdw==