apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: dev-argoapp
data:
  RABBIT_URL: "amqp://guest:guest@rabbitmq.dev.svc.cluster.local:5672"
  REDIS_URL: "redis.dev.svc.cluster.local:6379"
  SERVER_ADDR: "0.0.0.0:8080"
  EXCHANGE: "main_exchange"
  QUEUE_BACK: "backend_queue"
  QUEUE_DB: "db_queue"
  QUEUE_CACHE: "cache_queue"
  KEY_FRONT: "frontend_key"
  KEY_BACK: "backend_key"
  KEY_DB: "db_key"
  KEY_CACHE: "cache_key"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-db-config
  namespace: dev-argoapp
data:
  database.sql: |
    create database microservices;

    \c microservices

    create table messages (
      id serial primary key,
      message text not null,
      created timestamp not null
    );

