apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: dev-argoapp
type: Opaque
data:
  POSTGRES_URL: "cG9zdGdyZXM6Ly9wb3N0Z3JlczpkZW1vcHN3QHBvc3RncmVzLmRldi1hcmdvYXBwLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvbWljcm9zZXJ2aWNlcw=="
  POSTGRES_PASSWORD: "ZGVtb3Bzdw=="