apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: dev-argoapp
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: dashboard
    port: 15672
    targetPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: dev-argoapp
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: dev-argoapp
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: dev-argoapp
spec:
  type: NodePort
  selector:
    app: server
  ports:
  - port: 8080
    targetPort: 8080

